version: 2.1


jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-npm-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - "dist/*"

  release:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - restore_cache:
          keys: 
            - v1-npm-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker
      - run:
          name: build and push subzero-cli-tools docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build --build-arg APGDIFF_VERSION=2.6.1 -t subzero-cli-tools .
            docker tag subzero-cli-tools subzerocloud/subzero-cli-tools:$CIRCLE_TAG
            docker tag subzero-cli-tools subzerocloud/subzero-cli-tools:latest

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Move files from workspace
          command: |
            mkdir -p dist
            mv /tmp/workspace/dist .
      - run: 
          name: Publish
          # This fails silently TODO!!! fix
          command: |
            [ -f dist/subzero.js ] && npm publish
            docker push subzerocloud/subzero-cli-tools:$CIRCLE_TAG
            docker push subzerocloud/subzero-cli-tools:latest
      

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
